spring.application.name=Ostadassignment25

spring.datasource.url=jdbc:postgresql://localhost:5432/file_share
spring.datasource.username=postgres
spring.datasource.password=khalid
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

file.upload-dir=uploads
