spring.application.name=OstadAssignment26

spring.datasource.url=jdbc:postgresql://localhost:5432/github_reader
spring.datasource.username=postgres
spring.datasource.password=khalid

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

github.root.readme=https://raw.githubusercontent.com/abusaeed2433/JavaInREADME/main/README.md